version: 2.1
jobs:
  build:
    docker:
      - image: cimg/php:8.1
      - image: cimg/mysql:8.0
    working_directory: ~/coachtech-flea-market/src
    steps:
      - checkout
      - run: sudo apt update && sudo apt install -y libfreetype6-dev libjpeg62-turbo-dev libpng-dev zlib1g-dev default-mysql-client libzip-dev unzip cron mariadb-client

      - run: |
          sudo docker-php-ext-configure gd --with-freetype --with-jpeg
          sudo docker-php-ext-install zip gd

      - run:
          name: Docker php extensions install
          command: sudo docker-php-ext-install pdo_mysql

      - run:
          name: Install PHP libraries
          working_directory: src
          command: composer install

      - run:
          command: php artisan migrate --env=testing
      - run:
          name: Run PHPUnit
          working_directory: src
          command: vendor/bin/phpunit tests/Feature/