version: 2.1
jobs:
  build:
    docker:
      - image: cimg/php:8.1-node
      - image: cimg/mysql:8.0
    working_directory: ~/coachtech-flea-market/src
    steps:
      - checkout
      - run: sudo apt update

      - run:
          name: Docker php extensions install
          command: sudo docker-php-ext-install pdo_mysql

      - run:
          name: Install PHP libraries
          working_directory: src
          command: composer install

      - run:
          command: php artisan migrate --env=testing
      - run:
          name: Run PHPUnit
          working_directory: src
          command: vendor/bin/phpunit tests/Feature/