version: 2.1
jobs:
  build:
    docker:
      - machine: true
    steps:
      - checkout
      - run:
          name: Setup docker
          command: |
            docker-compose up -d --build
            docker-compose run php composer install

      - run:
          name: Setup Laravel
          command: |
            cp .env.testing .env
            docker-compose run php php artisan migrate --env=testing

      - run:
          name: Run PHPUnit
          # working_directory: src
          command: vendor/bin/phpunit tests/Feature/