version: 2.1
jobs:
  build:
    docker:
      - image: cimg/php:8.1-node
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: SHA256:DMSCPSBHAOM+3ybD4wROC6kvR50uacu7bfob6ZfAHm4
      - run:
          name: aws deploy
          command: |
            ssh -o StrictHostKeyChecking=no -t ec2-user@${HOST_NAME} 'cd /var/www/coachtech-flea-market/ &&\
            git pull origin main &&\
            sudo yum install -y php-xml &&\
            cd src/ &&\
            composer update &&\
            composer install &&\
            sudo yum install php php-devel php-opcache php-mbstring php-xml &&\
            sudo cp .env.example .env &&\
            php artisan key:generate'



