version: 2.1
jobs:
  build:
    docker:
      - image: cimg/php:8.1
    working_directory: ~/coachtech-flea-market/src
    steps:
      - checkout:
        path: ~/coachtech-flea-market

  test:
    docker:
      - image: cimg/php:8.1
      - image: circleci/mysql:5.5
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: demo_test
          MYSQL_USER: root
        environment:
          BUNDLE_JOBS: "3"
          BUNDLE_RETRY: "3"
          APP_DATABASE_HOST: "127.0.0.1"
        working_directory: ~/coachtech-flea-market/src
        steps:
          - checkout:
            path: ~/coachtech-flea-market
      - run:
          name: update apt-get
          command: sudo apt-get update
      # - run: sudo composer self-update --2

      - run:
          name: Docker php extensions install
          command: sudo docker-php-ext-install pdo_mysql zip gd
      # - restore_cache:
      #     keys:
      #       - v1-dependencies-{{ checksum "composer.json" }}
      #       - v1-dependencies-

      - run:
          name: Install PHP libraries
          working_directory: src
          command: composer install
      # - run: npm ci
      # - run: npm run dev
      # - save_cache:
      #     paths:
      #       - ./vendor
      #     key: v1-dependencies-{{ checksum "composer.json" }}

      - run:
          command: php artisan migrate --env=testing
      - run:
          name: Run PHPUnit
          working_directory: src
          command: vendor/bin/phpunit tests/Feature/

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build